name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install node@12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install yarn
        uses: comchangs/action-yarn@v0.1-beta

      - name: yarn install, build and test
        run: |
          yarn
          yarn run dev

      - name: Install and run composer
        uses: nick-zh/composer-php@master
        with:
          action: "install"

      - name: Setup environment variables
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Setup sqlite
        run: touch database/database.sqlite

      - name: Migrate and seed database
        run: |
          php artisan migrate
          php artisan db:seed

      - name: Run PHPUnit
        run: php7.3 vendor/bin/phpunit
